{
 "title": "Kafka Broker Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result({__name__=\"kafka_brokers\"})"
    }
   },
   {
    "name": "group",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_consumer_group_members{cluster=\"$cluster\"},group)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partitions{cluster=\"$cluster\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Brokers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic List",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "max by(topic) (kafka_topic_partitions{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Consumer Group List",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by(group) (kafka_consumer_group_members{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Topic Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_topic_partitions{cluster=\"$cluster\", topic=~\"$topic\"}"
    },
    {
     "expr": "kafka_topic_replication_factor_ratio{cluster=\"$cluster\", topic=~\"$topic\"}"
    },
    {
     "expr": "kafka_topic_log_retention_period_seconds{cluster=\"$cluster\", topic=~\"$topic\"}"
    }
   ]
  },
  { "title": "Consumer Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$group",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_group_members{cluster=\"$cluster\",group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Consumer Group Offset",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_group_offset_sum_ratio{cluster=\"$cluster\", group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Consumer Group Partition Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "kafka_consumer_group_offset_ratio{cluster=\"$cluster\", group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_group_lag_sum_ratio{group=\"$group\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Partition Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_group_lag_ratio{group=\"$group\"}) by (partition)",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  }
 ]
}